Fix block count calculation for rgba8 TEX
LeagueToolkit/LeagueToolkit pull request #281
Opened 2023-06-06 00:12 UTC by Morilli

This (fixes) https://github.com/Crauzer/Obsidian/issues/195.
The underlying issue is that `BcDecoder.GetBlockCount` assumed a fixed 4x4 size per block, which may be valid for all DXTn formats but doesn't hold true for RGBA8, which has 1x1 "blocks". So, I've created a custom function that does the calculation with RGBA8 in mind.

Note that I haven't checked whether ETC1/ETC2 are correct now, but it can't be worse than before.

2023-06-06 21:55 UTC, Crauzer requested changes

2023-06-06 21:55 UTC, Crauzer commented on src/LeagueToolkit/Core/Renderer/Texture.cs
> +        private static void CalculateBlockCount(
Can we please change this to return a tuple instead of `out` parameters ?

2023-06-09 09:08 UTC, aspeLoL commented
Hi!
How much we need wait for the update?
I have the same problem, can't open these files :/

2023-06-13 13:38 UTC, Crauzer approved these changes

2023-06-13 13:38 UTC, merged